spring:
  application:
    name: aixbox-admin
  profiles:
    active: local

aixbox:
  info:
    version: 1.0.0
    base-package: com.aixbox

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名转换
    auto-mapping-behavior: full # 字段映射